DROP DATABASE IF EXISTS CSIS3280MockFinal;
CREATE DATABASE CSIS3280MockFinal;
USE CSIS3280MockFinal;

CREATE TABLE FishLog (
    id INT PRIMARY KEY AUTO_INCREMENT,
    weight INT NOT NULL,
    length INT NOT NULL,
    species VARCHAR(50) NOT NULL,
    logstamp DATETIME
);